baseURL = "https://benscofield.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ben Scofield"
theme = "hugo-material-blog"
googleAnalytics = "UA-891855-6"

[author]
  name = "Ben Scofield"

[permalinks]
  posts = "/:year/:month/:title/"

# Main menu
[[languages.en.menu.main]]
  url = "/posts"
  name = "Posts"
  weight = 1

[[languages.en.menu.main]]
  url = "/now"
  name = "Now"
  weight = 2
