baseURL = "https://benscofield.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 8
title = "Ben Scofield"
theme = "hugo-vitae"
googleAnalytics = "UA-891855-6"

[author]
  name = "Ben Scofield"

[permalinks]
  posts = "/:year/:month/:title/"

# Main menu
[[menu.main]]
  url = "/posts"
  name = "Posts"
  weight = 1

[[menu.main]]
  url = "/now"
  name = "Now"
  weight = 2

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/bscofield"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
cmd = "https://twitter.com/bscofield"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:me@benscofield..com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"


[params]
	avatar = "/img/marmalade.png"

  nofeedSections = ["now"]

  subtitle = "... rarely updated"